### ISSUE TITLE
seems min_support does not work well as expected 

### ISSUE THREAD

**Issue by Madhuka** [bartdag/pymining#2]
report = itemmining.relim(relim_input, min_support=4)

here is dataset I used to test transactions = (('1','14043','6686','8302','8298'),('1','14043','6686','8298','8302'),('1','14043','6686','8302','8298'),('1','14043','6686','8298','8302'),('1','14043','8302','6686','8298'),('1','14043','6686','8302','8298'),('1','14043','6686','8302','8298'),('1','14043','6686','8298','8302'),('1','14043','8302','8298','6686'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8302','8298'),('1','14043','6686','8302','8298'),('1','14043','6686','8302','8298'),('1','14043','8298','8302','6686'),('1','14043','6686','8302','8298'),('1','14043','6686','8302','8298'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','8302','8298','6686'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','8298','8302','6686'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8302','8298'),('1','14043','6686','8302','8298'),('1','14043','6686','8298','8302'),('1','14043','6686','8302','8298'),('1','14043','8302','8298','6686'),('1','14043','8302','8298','6686'),('1','14043','6686','8302','8298'),('1','14043','8302','6686','8298'),('14043','1','6686','8302','8298'),('1','14043','6686','8298','8302'),('1','14043','6686','8302','8298'),('1','14043','8302','6686','8298'),('1','14043','6686','8302','8298'),('8298','14043','6686','8302','1'),('1','14043','8302','6686','8298'),('1','14043','6686','8302','8298'),('1','14043','8298','6686','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8302','8298'),('1','14043','6686','8298','8302'),('1','14043','8298','8302','6686'),('1','14043','6686','8298','8302'),('1','14043','6686','8302','8298'),('1','14043','8302','8298','6686'),('1','14043','8298','8302','6686'),('6686','1','8298','8302','14043'),('1','14043','8302','8298','6686'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','8302','14043','6686','8298'),('1','8298','14043','6686','8302'),('1','8298','8302','14043','6686'),('1','8302','14043','8298','6686'),('1','8298','14043','6686','8302'),('1','8298','8302','14043','6686'),('1','8298','8302','14043','6686'),('1','8302','14043','6686','8298'),('1','8298','8302','14043','6686'),('1','8298','8302','14043','6686'),('1','8298','8302','14043','6686'),('6686','1','14043','8298','8302'),('1','8298','8302','14043','6686'),('1','6686','14043','8302','8298'),('1','8302','14043','6686','8298'),('1','8302','8298','14043','6686'),('1','8302','14043','8298','6686'),('14043','6686','1','8298','8302'),('1','8302','14043','6686','8298'),('1','8302','8298','14043','6686'),('1','8302','8298','14043','6686'),('1','8298','8302','14043','6686'),('8298','8302','1','14043','6686'),('1','8302','14043','6686','8298'))

out put 
{frozenset(['1', '8298', '14043']): 84, frozenset(['8298', '8302', '6686', '14043']): 84, frozenset(['1', '8298', '8302', '6686']): 84, frozenset(['8298', '14043']): 84, frozenset(['8298']): 84, frozenset(['8302', '14043']): 84, frozenset(['8302', '6686']): 84, frozenset(['6686', '14043']): 84, frozenset(['8298', '6686', '14043']): 84, frozenset(['1', '6686']): 84, frozenset(['1', '14043']): 84, frozenset(['1', '8298', '8302']): 84, frozenset(['1', '6686', '14043']): 84, frozenset(['1', '8298', '6686', '14043']): 84, frozenset(['8298', '6686']): 84, frozenset(['8302', '6686', '14043']): 84, frozenset(['1']): 84, frozenset(['1', '8298']): 84, frozenset(['1', '8298', '8302', '6686', '14043']): 84, frozenset(['8298', '8302', '14043']): 84, frozenset(['1', '8302']): 84, frozenset(['1', '8298', '6686']): 84, frozenset(['1', '8302', '6686']): 84, frozenset(['1', '8298', '8302', '14043']): 84, frozenset(['6686']): 84, frozenset(['14043']): 84, frozenset(['1', '8302', '14043']): 84, frozenset(['8298', '8302']): 84, frozenset(['8302']): 84, frozenset(['1', '8302', '6686', '14043']): 84, frozenset(['8298', '8302', '6686']): 84}

code 
from pymining import itemmining

cluster07_transactions = (('1','14043','6686','8302','8298'),('1','14043','6686','8298','8302'),('1','14043','6686','8302','8298'),('1','14043','6686','8298','8302'),('1','14043','8302','6686','8298'),('1','14043','6686','8302','8298'),('1','14043','6686','8302','8298'),('1','14043','6686','8298','8302'),('1','14043','8302','8298','6686'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8302','8298'),('1','14043','6686','8302','8298'),('1','14043','6686','8302','8298'),('1','14043','8298','8302','6686'),('1','14043','6686','8302','8298'),('1','14043','6686','8302','8298'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','8302','8298','6686'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','8298','8302','6686'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8302','8298'),('1','14043','6686','8302','8298'),('1','14043','6686','8298','8302'),('1','14043','6686','8302','8298'),('1','14043','8302','8298','6686'),('1','14043','8302','8298','6686'),('1','14043','6686','8302','8298'),('1','14043','8302','6686','8298'),('14043','1','6686','8302','8298'),('1','14043','6686','8298','8302'),('1','14043','6686','8302','8298'),('1','14043','8302','6686','8298'),('1','14043','6686','8302','8298'),('8298','14043','6686','8302','1'),('1','14043','8302','6686','8298'),('1','14043','6686','8302','8298'),('1','14043','8298','6686','8302'),('1','14043','6686','8298','8302'),('1','14043','6686','8302','8298'),('1','14043','6686','8298','8302'),('1','14043','8298','8302','6686'),('1','14043','6686','8298','8302'),('1','14043','6686','8302','8298'),('1','14043','8302','8298','6686'),('1','14043','8298','8302','6686'),('6686','1','8298','8302','14043'),('1','14043','8302','8298','6686'),('1','14043','6686','8298','8302'),('1','14043','6686','8298','8302'),('1','8302','14043','6686','8298'),('1','8298','14043','6686','8302'),('1','8298','8302','14043','6686'),('1','8302','14043','8298','6686'),('1','8298','14043','6686','8302'),('1','8298','8302','14043','6686'),('1','8298','8302','14043','6686'),('1','8302','14043','6686','8298'),('1','8298','8302','14043','6686'),('1','8298','8302','14043','6686'),('1','8298','8302','14043','6686'),('6686','1','14043','8298','8302'),('1','8298','8302','14043','6686'),('1','6686','14043','8302','8298'),('1','8302','14043','6686','8298'),('1','8302','8298','14043','6686'),('1','8302','14043','8298','6686'),('14043','6686','1','8298','8302'),('1','8302','14043','6686','8298'),('1','8302','8298','14043','6686'),('1','8302','8298','14043','6686'),('1','8298','8302','14043','6686'),('8298','8302','1','14043','6686'),('1','8302','14043','6686','8298'))
relim_input = itemmining.get_relim_input(cluster07_transactions)
report = itemmining.relim(relim_input, min_support=4)
print (report)

**Comment by bartdag** [comment]
What is the problem with the provided output? It seems you are provided the same sequence of five numbers 84 times.
